name: Publish to NPM Packages

on:
  push:
    branches:
      - main
        
jobs:
  build-deploy-bump:
    uses: bob-obringer/github-workflows/.github/workflows/package-build-publish-bump.yaml@main
    secrets: inherit